project = "canny_no_patching_no_augmentations"
patching = "False"
augmentations = "False"
image_dir = "C:/Users/paras/eelgrass/Reports/13074_csv_image_annotation_report/Data_Images_All/"
mask_dir = "C:/Users/paras/eelgrass/Reports/13074_csv_image_annotation_report/Data_Masks_All/"
test_images_dir = "C:/Users/paras/eelgrass/data_formatted/cover/cropped/"
test_masks_dir = "C:/Users/paras/eelgrass/data_train_converted/"
predicted_masks_dir = "C:/Users/paras/eelgrass/Predicted_masks/"
predicted_covers_dir = "C:/Users/paras/eelgrass/Predicted_covers/"
save_valid_splits = "/home/parasm/Projects/validation_splits/"
save_model_weights = "C:/Users/paras/eelgrass/model_weights/"
model = "Unet"
pretrained = "False"
seed = 10
batch_size = 1
learning_rate = 1e-4
epochs = 100
optimizer = "SGD"
loss_val = "BCEWithLogitsLoss"
num_folds = 10
scheduler = "None"
