project = "patching_no_augmentations"
patching = "True"
augmentations = "False"
image_dir = "/home/parasm/Projects/Data_Images_All/"
mask_dir = "/home/parasm/Projects/Data_Masks_All/"
test_images_dir = "/home/parasm/Projects/cropped/"
test_masks_dir = "/home/parasm/Projects/data_train_converted/"
predicted_masks_dir = "/home/parasm/Projects/predicted_masks/"
save_valid_splits = "/home/parasm/Projects/validation_splits/"
save_model_weights = "/home/parasm/Projects/model_weights/"
model = "Unet"
pretrained = "False"
seed = 10
batch_size = 2
learning_rate = 1e-4
epochs = 100
optimizer = "SGD"
loss_val = "BCEWithLogitsLoss"
num_folds = 10
scheduler = "None"
